# Generated by Django 5.1.3 on 2024-11-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="expiry",
            field=models.DateField(auto_now=True),
        ),
    ]
